// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Dados.date
{
    public partial class Teste
    {
        public string Teste1 { get; set; }
        public string Horario { get; set; }
    }
}